### ISSUE TITLE
Typo about org value in comment?

### ISSUE THREAD

**Issue by Costava** [cesarblum/sectorforth#1]
https://github.com/cesarblum/sectorforth/blob/a34ab7f802b6fa69fae040a3aceb87d1bdabbc71/sectorforth.asm#L26-L28

The part `0x0500 << 4 + 0x7700 == 0x7c00` seems to have a typo.

I expect `0x0050` instead of `0x0500` in order for the expression to be true.
i.e. `0x0050 << 4 + 0x7700 == 0x7c00`

Am I misunderstanding?

**Comment by cesarblum** [comment]
You're right! Fixed in 03293c070d94bd6afb226f5c134e03ca8c372042. Thanks!
